In [147]:
import os

import pandas as pd
import numpy as np
from glob import glob

In [148]:
cache_dir = "./wandb_cache"

In [149]:
csvs = glob(f"{cache_dir}/*.csv")

In [150]:
#  concat 
df = pd.concat([pd.read_csv(csv) for csv in csvs])
df = df[df['target_character'] == 2]
df

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/acc_imp_perc,Evaluation/exist_imp_perc,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability
0,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b2w1_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.044444,0.633333,0.283333,29.000000,2.866667,0.000000,0.066667,0.066667,0.066667,0.200000
1,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b2w1_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.000000,0.016667,0.016667,26.000002,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
2,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b2w1_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.000000,0.016667,0.016667,26.000002,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
0,pe-cot_it-6_fit-hr_exp-llama33_t-sce_chr-2_1_s-2,finished,2,cot,llama-33,2,llama33,hr,6,0,...,0.811111,1.000000,1.000000,26.074074,0.500000,0.066667,0.766667,1.666667,0.833333,0.900000
1,pe-cot_it-6_fit-hr_exp-llama33_t-sce_chr-2_1_s-2,finished,2,cot,llama-33,2,llama33,hr,6,0,...,0.144444,0.950000,0.516667,28.000002,2.566667,0.000000,0.166667,0.266667,0.133333,0.233333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,o62jjmhj,finished,2,cot,gpt-4o,2,vision,hr,6,0,...,0.544445,0.966667,0.900000,26.074074,1.366667,0.000000,0.633333,1.000000,0.600000,0.900000
2,o62jjmhj,finished,2,cot,gpt-4o,2,vision,hr,6,0,...,0.366667,0.983333,0.650000,26.615385,1.866667,0.033333,0.366667,0.733333,0.366667,0.433333
3,o62jjmhj,finished,2,cot,gpt-4o,2,vision,hr,6,0,...,0.233333,0.833333,0.533333,26.800001,2.300000,0.000000,0.300000,0.400000,0.266667,0.333333
4,o62jjmhj,finished,2,cot,gpt-4o,2,vision,hr,6,0,...,0.244444,0.800000,0.483333,26.909092,2.233333,0.033333,0.300000,0.433333,0.266667,0.366667
5,o62jjmhj,finished,2,cot,gpt-4o,2,vision,hr,6,0,...,0.266667,0.733333,0.566667,26.461540,2.133333,0.066667,0.333333,0.466667,0.400000,0.433333

In [151]:
# Filter data where Evaluation/llm_iteration == 1 and Evaluation/acc_imp_perc == 0.0
iteration_1 = df[(df['Evaluation/llm_iteration'] == 1) & (df['Evaluation/acc_imp_perc'] < 0.2)]

# Filter data where Evaluation/llm_iteration == 6 and Evaluation/acc_imp_perc == 1.0
iteration_6 = df[(df['Evaluation/llm_iteration'] > 5) & (df['Evaluation/acc_imp_perc'] >= 0.8)]



# Find run_ids that meet both conditions
filtered_run_ids = set(iteration_1['run_id']).intersection(set(iteration_6['run_id']))

# Convert the result to a DataFrame for easier handling
df_filtered = df[df['run_id'].isin(filtered_run_ids)]
df_filtered

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/acc_imp_perc,Evaluation/exist_imp_perc,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability
0,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.000000,0.716667,0.116667,26.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.066667
1,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.000000,0.033333,0.033333,26.000002,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
2,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.000000,0.016667,0.016667,26.000002,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
3,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.000000,0.016667,0.016667,26.000002,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
4,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.000000,0.033333,0.033333,26.000002,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
5,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.100000,0.766667,0.766667,26.000002,2.700000,0.000000,0.133333,0.166667,0.133333,1.000000
6,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.100000,0.766667,0.766667,26.000002,2.700000,0.000000,0.133333,0.166667,0.133333,1.000000
7,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.100000,0.766667,0.766667,26.000002,2.700000,0.000000,0.133333,0.166667,0.133333,1.000000
8,vznj7ns4,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.800000,0.833333,0.833333,26.000002,0.600000,0.000000,0.933333,1.466667,0.933333,1.000000
0,pe-cot_it-6_fit-hr_exp-llama32sa_t-sce_chr-2_1...,finished,2,cot,llama-32,2,llama32sa,hr,6,5,...,0.000000,0.950000,0.166667,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,pe-cot_it-6_fit-hr_exp-llama32sa_t-sce_chr-2_1...,finished,2,cot,llama-32,2,llama32sa,hr,6,5,...,0.666667,0.966667,0.850000,27.181820,0.933333,0.066667,0.666667,1.333333,0.733333,0.733333
2,pe-cot_it-6_fit-hr_exp-llama32sa_t-sce_chr-2_1...,finished,2,cot,llama-32,2,llama32sa,hr,6,5,...,0.466667,0.650000,0.566667,27.478262,1.600000,0.000000,0.766667,0.633333,0.633333,0.766667
3,pe-cot_it-6_fit-hr_exp-llama32sa_t-sce_chr-2_1...,finished,2,cot,llama-32,2,llama32sa,hr,6,5,...,0.033333,0.550000,0.150000,27.000000,2.900000,0.000000,0.066667,0.033333,0.000000,0.066667
4,pe-cot_it-6_fit-hr_exp-llama32sa_t-sce_chr-2_1...,finished,2,cot,llama-32,2,llama32sa,hr,6,5,...,0.666667,1.000000,0.883333,26.300001,1.000000,0.000000,0.666667,1.333333,0.533333,0.666667
5,pe-cot_it-6_fit-hr_exp-llama32sa_t-sce_chr-2_1...,finished,2,cot,llama-32,2,llama32sa,hr,6,5,...,1.000000,1.000000,1.000000,26.066668,0.000000,0.000000,1.000000,2.000000,0.900000,1.000000
0,tcxfnuaj,finished,2,tot,chatgpt-4o,2,def,hr,6,0,...,0.100000,0.983333,0.550000,26.444445,2.466667,0.233333,0.000000,0.300000,0.166667,0.300000
1,tcxfnuaj,finished,2,tot,chatgpt-4o,2,def,hr,6,0,...,0.911111,1.000000,1.000000,26.000000,0.100000,0.166667,0.800000,1.933333,0.966667,0.966667
2,tcxfnuaj,finished,2,tot,chatgpt-4o,2,def,hr,6,0,...,0.822222,1.000000,0.983333,26.923079,0.400000,0.133333,0.733333,1.733333,0.800000,0.866667
3,tcxfnuaj,finished,2,tot,chatgpt-4o,2,def,hr,6,0,...,0.900000,1.000000,0.983333,26.344828,0.100000,0.200000,0.766667,1.933333,0.966667,0.966667
4,tcxfnuaj,finished,2,tot,chatgpt-4o,2,def,hr,6,0,...,0.933333,1.000000,1.000000,26.285715,0.200000,0.000000,0.933333,1.866667,0.900000,0.933333
5,tcxfnuaj,finished,2,tot,chatgpt-4o,2,def,hr,6,0,...,0.855556,1.000000,0.983333,26.692308,0.400000,0.033333,0.833333,1.733333,0.733333,0.866667
0,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.000000,0.700000,0.016667,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.644445,0.816667,0.816667,26.000002,1.066667,0.000000,0.800000,1.133333,0.800000,1.000000
2,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.177778,0.916667,0.916667,26.000002,2.266667,0.200000,0.066667,0.466667,0.266667,1.000000
3,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.511111,0.550000,0.550000,26.000002,1.400000,0.066667,0.766667,0.766667,0.833333,1.000000
4,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.533333,0.600000,0.600000,26.000002,1.200000,0.200000,0.633333,0.966667,0.833333,1.000000
5,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.688889,0.966667,0.966667,26.000002,0.633333,0.300000,0.566667,1.500000,0.866667,1.000000
6,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.877778,1.000000,1.000000,26.000002,0.033333,0.333333,0.666667,1.966667,1.000000,1.000000
7,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.477778,0.800000,0.766667,26.000000,0.966667,0.600000,0.300000,1.133333,0.900000,0.966667
8,d9d9ittn,finished,2,got,gpt-4o,2,def,hr,9,0,...,0.611111,0.866667,0.866667,26.000002,0.666667,0.500000,0.466667,1.366667,0.966667,1.000000
0,pe-got_it-6_fit-hr_exp-llama32_t-sce_chr-2_1_s-7,finished,2,got,llama-32,2,llama32,hr,6,0,...,0.000000,0.983333,0.316667,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,pe-got_it-6_fit-hr_exp-llama32_t-sce_chr-2_1_s-7,finished,2,got,llama-32,2,llama32,hr,6,0,...,0.277778,0.950000,0.633333,26.307693,2.100000,0.066667,0.266667,0.566667,0.300000,0.433333
2,pe-got_it-6_fit-hr_exp-llama32_t-sce_chr-2_1_s-7,finished,2,got,llama-32,2,llama32,hr,6,0,...,0.500000,1.000000,0.766667,27.222223,1.400000,0.100000,0.466667,1.033333,0.566667,0.600000
3,pe-got_it-6_fit-hr_exp-llama32_t-sce_chr-2_1_s-7,finished,2,got,llama-32,2,llama32,hr,6,0,...,0.211111,0.900000,0.650000,26.727274,2.200000,0.166667,0.166667,0.466667,0.333333,0.366667
4,pe-got_it-6_fit-hr_exp-llama32_t-sce_chr-2_1_s-7,finished,2,got,llama-32,2,llama32,hr,6,0,...,0.500000,0.983333,0.816667,26.600000,1.366667,0.133333,0.466667,1.033333,0.600000,0.666667
5,pe-got_it-6_fit-hr_exp-llama32_t-sce_chr-2_1_s-7,finished,2,got,llama-32,2,llama32,hr,6,0,...,0.833333,0.950000,0.950000,26.000002,0.133333,0.366667,0.633333,1.866667,1.000000,1.000000
0,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b0w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.000000,0.300000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b0w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.011111,0.050000,0.050000,26.000002,2.966667,0.000000,0.033333,0.000000,0.033333,1.000000
2,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b0w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.088889,0.850000,0.850000,26.000002,2.733334,0.000000,0.166667,0.100000,0.166667,1.000000
3,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b0w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.500000,0.750000,0.750000,26.000002,1.300000,0.200000,0.500000,1.000000,0.700000,1.000000
4,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b0w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.555556,0.683333,0.683333,26.000002,1.333333,0.000000,0.766667,0.900000,0.766667,1.000000
5,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b0w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.888889,0.916667,0.916667,26.000002,0.333333,0.000000,0.966667,1.700000,0.966667,1.000000
0,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b1w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.000000,0.616667,0.083333,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b1w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.011111,0.033333,0.033333,26.000002,2.966667,0.000000,0.033333,0.000000,0.033333,1.000000
2,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b1w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.000000,0.000000,0.000000,26.000002,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
3,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b1w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.155556,0.383333,0.383333,26.000002,2.533334,0.000000,0.266667,0.200000,0.266667,1.000000
4,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b1w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.988889,1.000000,1.000000,26.000002,0.000000,0.033333,0.966667,2.000000,1.000000,1.000000
5,pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b1w2_chr-...,finished,2,got,gpt-4o,2,aux,hr,6,0,...,0.888889,0.933333,0.933333,26.000002,0.333333,0.000000,0.966667,1.700000,0.966667,1.000000

In [152]:
# download image from wandb
import wandb
import os
PROJECT_NAME = "scenario"
ENTITY_NAME = "inchangbaek4907"

In [153]:
cherry_dir = "cherry"
os.makedirs(cherry_dir, exist_ok=True)

for idx, row in df_filtered.iterrows():

    api = wandb.Api()
    run = api.run(f"{ENTITY_NAME}/{PROJECT_NAME}/{row['run_id']}")
    
    base_url = run.files()[0].client.app_url
    files = run.files()
    for file in files:
        name = file.name
        url = file.directUrl
        
    
        # if not name includes "rollout" and "png", skip it
        if "rollout" not in name or "png" not in name:
            continue
        
        iteration = name.split("/")[2]
        filename = name.split("/")[-1]
        
        origin_path = os.path.join(".temp", 'media', 'images', iteration, 'rollout', filename)
        target_path = os.path.join(cherry_dir, f'chr_{row["target_character"]}', row["run_id"], iteration)
        

        file.download(exist_ok=True, root=".temp")

        # copy file
        os.makedirs(target_path, exist_ok=True)
        os.system(f"cp {origin_path} {target_path}")
        print(f"cp {origin_path} {target_path}")

cp .temp/media/images/Iteration_1/rollout/images_350_8445ed8f9c6812500940.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_351_63f1746f7faa49314d50.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_352_5843f953a0d492a604d0.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_353_47886503eadf79fdc577.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_354_7869c301722e75459aaf.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_355_18599765c3b1631720c3.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_356_29d9dda6930fdfe34521.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_357_6a9a2dcde7c18b0b64f8.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_358_d687b895a2503987912a.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_359_2c576115da0e45b4c672.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_360_33992109e34251b9efa6.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_361_dd042afb00e013ab1874.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_362_8f1fb4c628853fcf2ce7.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_363_5ce3fedb765de7bcbdf7.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_364_19c65ae9ed71a1c9b0c6.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_365_d372cd009df10906cdb3.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_366_2abc5feb86d7135f747d.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_367_81af44aa1a5a60f559b0.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_368_62846e49e29860eb8b0d.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_369_3e45d16a671fa6441ea0.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_370_10f14cc32c8a21dab699.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_371_5e05b02a932bad6f0b69.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_372_202ae9f2d226369de6d0.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_373_054e1b38c93b18bc562f.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_374_a657a55e86b9ca5b16f3.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_375_03fd0d2659bf23de3b63.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_376_722e9f740e6e311a2856.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_377_1289f58f5b0c9d764a17.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_378_0bf06bd4aa6df0dd3207.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_1/rollout/images_379_3705331a6e3305633b48.png cherry/chr_2/vznj7ns4/Iteration_1
cp .temp/media/images/Iteration_2/rollout/images_776_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_777_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_778_14b14105650033770217.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_779_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_780_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_781_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_782_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_783_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_784_f91151a46ddc0a32c8d0.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_785_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_786_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_787_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_788_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_789_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_790_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_791_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_792_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_793_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_794_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_795_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_796_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_797_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_798_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_799_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_800_c8006383e6454b030aa5.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_801_6122e218dbc762e72beb.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_802_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_803_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_804_d7381d4d9f898b05b5a1.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_2/rollout/images_805_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_2
cp .temp/media/images/Iteration_3/rollout/images_1202_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1203_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1204_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1205_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1206_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1207_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1208_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1209_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1210_f91151a46ddc0a32c8d0.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1211_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1212_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1213_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1214_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1215_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1216_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1217_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1218_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1219_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1220_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1221_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1222_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1223_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1224_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1225_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1226_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1227_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1228_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1229_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1230_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_3/rollout/images_1231_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_3
cp .temp/media/images/Iteration_4/rollout/images_1628_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1629_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1630_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1631_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1632_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1633_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1634_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1635_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1636_f91151a46ddc0a32c8d0.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1637_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1638_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1639_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1640_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1641_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1642_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1643_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1644_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1645_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1646_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1647_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1648_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1649_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1650_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1651_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1652_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1653_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1654_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1655_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1656_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_4/rollout/images_1657_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_4
cp .temp/media/images/Iteration_5/rollout/images_2054_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2055_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2056_14b14105650033770217.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2057_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2058_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2059_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2060_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2061_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2062_f91151a46ddc0a32c8d0.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2063_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2064_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2065_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2066_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2067_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2068_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2069_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2070_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2071_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2072_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2073_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2074_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2075_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2076_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2077_655b71eb4b26d6a69b29.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2078_c8006383e6454b030aa5.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2079_6122e218dbc762e72beb.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2080_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2081_0cc629f576f570887565.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2082_d7381d4d9f898b05b5a1.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_5/rollout/images_2083_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_5
cp .temp/media/images/Iteration_6/rollout/images_2480_1993680b9f3575f193fb.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2481_59835163c12cdcdbfcfd.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2482_b32de13467d88caebb14.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2483_6f38e2e4ef1fa51416fa.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2484_5d59c4b668fdcd02dd28.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2485_7641f3f5c9699ab458cd.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2486_4ce5ada56de64a43f316.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2487_10c8e442365c98d0a073.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2488_690cf77111015e8bb9fd.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2489_69c5fb2e58a1e28144e3.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2490_8a7d04b5b7cac3bb8218.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2491_bc0e7613b488d13f6ca0.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2492_54140fd524667263f4f5.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2493_514a7a7291f037e06b6d.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2494_95ac645e14e925b0e46a.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2495_82344d8afe55884fd3be.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2496_ed78e10894df008760a4.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2497_c3ea8dcd1077f200a76d.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2498_1eef08cbdfe0abed8eb2.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2499_9de4b2071f31466be161.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2500_a85a95dcb40ce5a2ae94.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2501_e7274dab9fd1cf414a43.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2502_36d7e45fc376e324aa0f.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2503_f1e6eafaeab72713cbd4.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2504_32803f12fcf3ded61e4f.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2505_209d41c2b24e5968ae0a.png cherry/chr_2/vznj7ns4/Iteration_6
cp .temp/media/images/Iteration_6/rollout/images_2506_50b908e1af0381abd564.png cherry/chr_2/vznj7ns4/Iteration_6

CommError: Could not find run <Run inchangbaek4907/scenario/pe-got_it-6_fit-hr_exp-aux_t-sce_aux-b0w2_chr-2_1_s-4 (not found)>